[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flowback = "D3T1iprZ1D43RGLPB8E57MQo2QW6xhtA6tQ4Cp3HqmB5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
